title: Ruby Conf Taiwan 2023
cfp_link: https://cfp.rubyconf.tw/activities/2023
register_link: https://rubytaiwan.kktix.cc/events/rubyconftw2023
interpretation_link_day1: https://meet.google.com/fnq-uokc-dkd
interpretation_link_day2: https://meet.google.com/znz-dpmk-ntw
interpretation_link_enabled: true
plugins:
  - jekyll-postcss

postcss:
  cache: false
